import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Product({ product, time }) {
  return (
    <>
      <Head>
        <title>ISR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{time}</h1>

        <p>{product.title}</p>
      </main>
    </>
  );
}

export async function getStaticPaths() {
  const paths = [
    {
      params: {
        productId: '1',
      },
    },
    {
      params: {
        productId: '2',
      },
    },
    {
      params: {
        productId: '3',
      },
    },
  ];

  return {
    paths,
    fallback: 'blocking',
  };
}

export async function getStaticProps({ params }) {
  const data = await fetch(
    `https://fakestoreapi.com/products/${params.productId}`
  );
  const product = await data.json();

  return {
    props: {
      product,
      time: new Date().toLocaleTimeString(),
    },
    revalidate: 60, // generate a new version of the after 60 seconds
  };
}
